version: '2'
services:
  www:
    image: cuckoohello/nginx
    container_name: nginx
    restart: always
    volumes:
      - ./site.d:/etc/nginx/site.d
      - ./letsencrypt:/etc/letsencrypt
      - ./log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
networks:
  default:
    external:
      name: service
