version: '2'
services:
  server:
    image: easypi/shadowsocks-libev
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - METHOD=aes-256-cfb
      - PASSWORD=password
    restart: always
networks:
  default:
    external:
      name: service
